#!/usr/bin/env python3
import sys
import urllib.parse

import requests


def main():
    try:
        id = sys.argv[1]
    except:
        id = input("Enter the iNaturalist observation id:")

    print(id)
    base_url = "https://api.inaturalist.org/v1/"
    observation_url = base_url + f"observations/{id}"

    result = requests.get(observation_url)

    data = result.json()
    print(data)
    observation_data = data["results"][0]
    audio_data_list = observation_data["observation_sounds"]

    for i, audio_data in enumerate(audio_data_list):
        print(f"URL for observation {str(i+1)} ")
        print_commons_url(observation_data, audio_data["sound"])
        print("=============== // =============")


def print_commons_url(observation_data, audio_data):

    print(audio_data)
    upload_params = {}

    audio_url = audio_data["file_url"]

    user_data = observation_data["user"]
    upload_params["audio_id"] = audio_data["id"]
    upload_params["audio_license"] = audio_data["license_code"]
    upload_params["user_id"] = user_data["id"]
    upload_params["user_name"] = observation_data["user"]["name"]
    upload_params["date"] = observation_data["observed_on"]
    upload_params["taxon"] = observation_data["taxon"]["name"]

    switcher = {"cc-by": "cc-by-4.0", "cc-by-sa": "cc-by-sa-4.0", "cc0": "Cc-zero"}

    print("https://commons.wikimedia.org/wiki/Special:Upload")

    print("====== Audio URL =====")
    print(audio_url)

    title = upload_params["taxon"] + " " + str(upload_params["audio_id"]) + ".wav"

    print("====== Summary ======")
    license = switcher[upload_params["audio_license"]]

    summary = (
        """{{Information"""
        + f"""
    |description={upload_params["taxon"]}
    |date={upload_params["date"]}
    |source=https://www.inaturalist.org/sounds/{str(upload_params["audio_id"])}
    |author=[https://www.inaturalist.org/users/{str(upload_params["user_id"])} {upload_params["user_name"]}]
    |permission=
    |other versions=
    """
        + """}}
        
    {{"""
        + f"iNaturalist|{id}"
        + """}}
        
        {{INaturalistreview}}
        """
        + f"""

    [[Category:{upload_params["taxon"]}]]"""
    )

    upload_page = "https://commons.wikimedia.org/wiki/Special:Upload"

    summary_for_url = urllib.parse.quote(summary)
    title_for_url = urllib.parse.quote(title)
    upload_url = (
        upload_page
        + f"?wpUploadDescription={summary_for_url}&wpLicense={license}&wpDestFile={title_for_url}&wpSourceType=url&wpUploadFileURL={audio_url}"
    )
    print(upload_url)


if __name__ == "__main__":
    main()
